# used kustomize create --namespace default --resources=service.yml,deployment.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Manifests that kustomize must track to be able to perform operations on them
# If not listed below, they do not exist in the eyes of kustomize
resources:
  # You could also use a github repo link here, has to be public I guess

  # - 01-alb-ingress.yml
  # - 02-ingress-gateway.yml
  - 03-virtual-service.yml
  - 04-service.yml
  - 05-deployment.yml
  - 06-requestauthentication.yml
  - 07-authorizationpolicy.yml
